name: Unity Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Activate Unity license
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2022.3.62f1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Build with unity-builder
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.62f1
          targetPlatform: StandaloneWindows64

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: build/*