name: Unity Build

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: ubuntu-latest
    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Activate Unity license
        uses: game-ci/unity-activate@v3
        with:
          unityVersion: 2022.3.62f1

      - name: Build project (Windows)
        uses: game-ci/unity-builder@v3
        with:
          unityVersion: 2022.3.62f1
          targetPlatform: StandaloneWindows64

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: build/*
          overwrite: true